export const DORMITORIES_SPORTS_HALL = "DORMITORIES_SPORTS_HALL";
export const EAST_OUTDOOR_SPORTS_FACILITIES = "EAST_OUTDOOR_SPORTS_FACILITIES";
export const EAST_SPORTS_HALL = "EAST_SPORTS_HALL";
export const MAIN_OUTDOOR_SPORTS_FACILITES = "MAIN_OUTDOOR_SPORTS_FACILITES";
export const MAIN_SPORTS_HALL = "MAIN_SPORTS_HALL";
export const SWIMMING_POOL = "SWIMMING_POOL";
